sudo: false
language: php
php:
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer install
script: php vendor/bin/phpunit --configuration ./phpunit.xml.dist
notifications:
  email:
    recipients:
    - dev@gennadyx.tech
    on_success: change
